apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
      listen       9000;
      server_name  localhost;
 
      location / {
         root   /usr/share/nginx/html;
         index  index.html index.htm;
      }
 
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
 
      # Jenkins
      location /jenkins/ {
         sendfile off;
         proxy_read_timeout      300;
         proxy_connect_timeout   300;
         proxy_redirect          off;
         proxy_http_version 1.1;
 
         proxy_set_header        X-Forwarded-Proto       $scheme;
         proxy_set_header        Host                    $http_host;
         #proxy_set_header        Host                    $host;
         proxy_set_header        X-Real-IP               $remote_addr;
         proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
         proxy_max_temp_file_size 0;
 
         proxy_pass              http://localhost:8080;
 
         access_log              /var/log/nginx/jenkins_access.log;
         error_log               /var/log/nginx/jenkins_error.log;
      }
      # gitea
      location /gitea/ {
         proxy_read_timeout      300;
         proxy_connect_timeout   300;
         proxy_redirect          off;
 
         proxy_set_header        X-Forwarded-Proto       $scheme;
         proxy_set_header        Host                    $http_host;
         #proxy_set_header        Host                    $host;
         proxy_set_header        X-Real-IP               $remote_addr;
         proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
 
         proxy_pass              http://localhost:3000/;
 
         access_log              /var/log/nginx/gitea_access.log;
         error_log               /var/log/nginx/gitea_error.log;
      }
    }
